const employees = [
  {
    id: 1,
    name: "Rahul Sharma",
    email: "employee1@example.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        title: "Complete UI Design",
        description: "Design the dashboard UI using Tailwind CSS",
        date: "2026-02-01",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Fix Login Bug",
        description: "Resolve login validation issue",
        date: "2026-01-28",
        category: "Bug Fix",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "API Integration",
        description: "Integrate employee API with frontend",
        date: "2026-01-30",
        category: "Development",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 2,
    name: "Amit Verma",
    email: "employee2@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        title: "Create Login Page",
        description: "Build responsive login page",
        date: "2026-02-02",
        category: "Frontend",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Update README",
        description: "Add project documentation",
        date: "2026-01-27",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Optimize Images",
        description: "Compress images for better performance",
        date: "2026-01-29",
        category: "Optimization",
        active: false,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Deploy App",
        description: "Deploy app on Netlify",
        date: "2026-02-03",
        category: "Deployment",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 3,
    name: "Neha Singh",
    email: "employee3@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        title: "Create REST API",
        description: "Build REST API using Express",
        date: "2026-01-26",
        category: "Backend",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Database Schema",
        description: "Design MongoDB schema",
        date: "2026-01-28",
        category: "Database",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Error Handling",
        description: "Improve backend error handling",
        date: "2026-02-01",
        category: "Backend",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 4,
    name: "Priya Patel",
    email: "employee4@example.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 0,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        title: "Test Application",
        description: "Perform unit testing",
        date: "2026-01-25",
        category: "Testing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Write Test Cases",
        description: "Create test cases for login module",
        date: "2026-01-27",
        category: "Testing",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Bug Reporting",
        description: "Report UI bugs",
        date: "2026-01-29",
        category: "QA",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 5,
    name: "Suresh Kumar",
    email: "employee5@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        title: "Client Meeting",
        description: "Discuss requirements with client",
        date: "2026-01-24",
        category: "Meeting",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Requirement Analysis",
        description: "Analyze client requirements",
        date: "2026-01-26",
        category: "Analysis",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Prepare Report",
        description: "Prepare weekly progress report",
        date: "2026-02-01",
        category: "Reporting",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
];

const admin = [
  {
    id: 101,
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
